name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-html flake8 flake8-html

    - name: Run tests and generate HTML reports
      run: |
        mkdir -p test_reports
        pytest --html=test_reports/test_report.html --self-contained-html

    - name: Run Flake8 and generate HTML reports
      continue-on-error: true
      run: |
        mkdir -p flake8_report
        flake8 ./game --format=html --htmldir=flake8_report || echo "Flake8 found issues"

    - name: List generated report files
      run: |
        echo "Listing test report files:"
        ls -l test_reports
        echo "Listing Flake8 report files:"
        ls -l flake8_report

    - name: Create ZIP archive of Flake8 report
      if: success() && steps.flake8_report.outputs.files-created == 'true'
      run: |
        zip -r flake8_report.zip flake8_report
        mv flake8_report.zip $GITHUB_WORKSPACE

    - name: Upload Flake8 report ZIP
      if: success() && steps.flake8_report.outputs.files-created == 'true'
      uses: actions/upload-artifact@v2
      with:
        name: flake8-report-zip
        path: $GITHUB_WORKSPACE/flake8_report.zip

    - name: Upload test reports
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: test_reports/test_report.html
