name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-html

    - name: Run tests and generate HTML reports
      run: |
        mkdir -p test_reports
        pytest --html=test_reports/test_report.html --self-contained-html

    - name: List generated report files
      run: |
        echo "Listing test report files:"
        ls -l test_reports

    - name: Upload test reports
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: test_reports/test_report.html
