name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover -s tests

    - name: Create Flake8 report directory
      run: mkdir -p flake8_report

    - name: Run Flake8
      continue-on-error: true
      run: |
        flake8 ./game --format=html --htmldir=flake8_report || echo "Flake8 found issues"

    - name: List Flake8 report files
      run: |
        echo "Listing Flake8 report files:"
        ls -l flake8_report

    - name: Upload test reports
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: test_report_*.html

    - name: Upload lint report
      uses: actions/upload-artifact@v2
      with:
        name: lint-report
        path: flake8_report/
